default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: app_development


test:
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: app_production
